site_name: python-app
site_description: Main documentation for the python-app
repo_url: https://github.com/lfalero14/python-app
edit_uri: edit/main/docs

plugins:
  - techdocs-core

docs_dir: docs

nav:
  - Overview:
      - Getting started: index.md
